sync configs via other tool

diff --git a/bin/wifi b/bin/wifi
--- a/bin/wifi
+++ b/bin/wifi
@@ -1,6 +1,6 @@
 #!/bin/bash -eu
 
-CONFIG_FILE=$(dirname $0)/../config/wifi.csv
+CONFIG_FILE=~/Documents/.dotfiles-secrets/wifi.csv
 
 if [ $# != 1 ]
 then
@@ -18,6 +18,12 @@ case $1 in
     ;;
 
   'set' )
+    if ! [ -f $CONFIG_FILE ]
+    then
+      echo "Not Found Setting File : $CONFIG_FILE"
+      exit 1
+    fi
+
     cat $CONFIG_FILE | while read CONFIG
     do
       ARR=(`echo $CONFIG | tr ',' ' '`)
